### PR TITLE
SortTable

### PR DESCRIPTION
**Pull request by TalesAugusto1**
table beeing sorted by last Update date now 👍

### CODE REVIEW

**Comment by TalesAugusto1** [comment]
🔥

**Review by KarinePistili — COMMENTED** [review]
@TalesAugusto1 Which issues are being sent on this pull request? Is it only the sort of the table? Or there is extra issue code?

**Comment by TalesAugusto1** [comment]
@KarinePistili The sortable table issue, now it's been sorted trough the last update date of each answer, and a parcial fix onto delete notifications.

**Comment by TalesAugusto1** [comment]
@KarinePistili The sortable table issue, now it's been sorted trough the last update date of each answer, and a parcial fix onto delete notifications.

**Review by KarinePistili — COMMENTED** [review]
reviewed

**Review by jvJUCA — APPROVED** [review]

**Pull request merged**
